version: '2'
services:
  some_virtuoso_server_with_data_preloaded:
    image: clariah/quad-log-example-virtuoso
    build: ./example-virtuoso-server
    ports:
      - "8890:8890"
  some_http_server:
    image: nginx
    volumes: 
      - rdfdumpwithresourcesync:/usr/share/nginx/html:ro
    ports: 
      - 8085:80
  the_quad_logger:
    build: ./quad-logger
    image: clariah/virtuoso-quad-log
    links: 
      - some_virtuoso_server_with_data_preloaded:virtuoso-source
    environment:
      - RUN_INTERVAL=60
      - INSERT_PROCEDURES=y
      - VIRTUOSO_HOST_NAME=virtuoso-source
      - MAX_QUADS_PER_DUMP_FILE=10
    volumes:
      - rdfdump:/datadir 
  resourcesync_generator:
    build: ./resourcesync-generator
    image: clariah/resourcesync-generator
    environment:
      - RUN_INTERVAL=60
      - HTTP_SERVER_URL=http://192.168.99.100:8085 #this is used to generate links in the xml files. It should be the public url
      - MAX_FILES_IN_ZIP=10
      - WRITE_SEPARATE_MANIFEST=True # Write separate manifest files in publish dir.
      - MOVE_RESOURCES=False # Move resources to publish dir. Set to True if individual resources should be published along side the zip files
    volumes:
      - rdfdump:/input
      - rdfdumpwithresourcesync:/output
  # todo: add an example crawler
  # an_example_crawler:
  #   image: huygensing/oai-rs-client
  #   link:
  #     - some_http_server:nginx
  #   port: 8180
volumes:
  rdfdump:
  rdfdumpwithresourcesync:
