version: '2'
services:
  some_virtuoso_server_with_data_preloaded:
    image: clariah/quad-log-example-virtuoso
    build: ./example-virtuoso-server
    ports:
      - "8890:8890"
  the_quad_logger:
    build: ./quad-logger
    image: clariah/virtuoso-quad-log
    links: 
      - some_virtuoso_server_with_data_preloaded:virtuoso-source
    environment:
      - RUN_INTERVAL=20
      - INSERT_PROCEDURES=y
      - VIRTUOSO_HOST_NAME=virtuoso-source
      - MAX_QUADS_PER_DUMP_FILE=10
    volumes:
      - stash1:/output
  the_graph_splitter:
    build: ./graph-splitter
    image: clariah/graph-splitter
    environment:
      - RUN_INTERVAL=20
    volumes:
      - stash1:/input
      - stash2:/output
  resourcesync_generator:
    build: ./resourcesync-generator
    image: clariah/resourcesync-generator
    environment:
      - RUN_INTERVAL=20
      - HTTP_SERVER_URL=http://192.168.99.100:8085 #this is used to generate links in the xml files. It should be the public url
      - MAX_FILES_COMPRESSED=10
      - WRITE_SEPARATE_MANIFEST=y # Write separate manifest files in publish dir.
      - MOVE_RESOURCES=n # Move resources to publish dir. Set to 'y' if individual resources should be published along side the compressed files
    volumes:
      - stash2:/input
      - stash3:/output
  some_http_server:
    image: nginx
    volumes:
      - stash3:/usr/share/nginx/html:ro
    ports:
      - 8085:80
  # todo: add an example crawler
  # an_example_crawler:
  #   image: huygensing/oai-rs-client
  #   link:
  #     - some_http_server:nginx
  #   port: 8180
volumes:
  stash1:
  stash2:
  stash3:
